runtime: python311
entrypoint: streamlit run app.py --server.port=8080 --server.enableCORS=false

instance_class: F2

env_variables:
  PORT: 8080

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 1
